# Generated by Django 4.2.2 on 2023-06-20 02:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_food_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_item',
            name='price',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
